# feature_filter = (0, 3)  # use only gyro
# feature_filter = (3, 6)  # use only magnetometer
#feature_filter = (6, 9)  # use only accelerometer
feature_filter = (0, 9)
batch_size = 32
split_ratio = 0.8
epochs = 500
device = 'cpu'
data_folder = 'data3'
